name: terraform-destroy

on:
  workflow_dispatch:

jobs:
  pipeline-terraform-destroy:
    name: Run terraform destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TERRAFORM_USER }}
          aws-secret-access-key: ${{ secrets.TERRAFORM_KEY }}
          aws-region: ${{ secrets.TERRAFORM_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Run terraform - destroy aws infra
        id: terraform-infra
        run: |
          terraform init
          terraform destroy -auto-approve

